### PR TITLE
documenting AWSTemplateFormatVersion requirement

### PR DESCRIPTION
**Pull request by PatMyron**
https://github.com/awslabs/aws-cfn-lint-visual-studio-code/issues/58

By submitting this pull request, I confirm that my contribution is made under the terms

### CODE REVIEW

**Comment by kddejong** [comment]
What version of the plugin are you using?  We did build some logic so that the AWSTemplateVersion is no longer required.  Since it isn't actually a required property in the CloudFormation template we had some logic built on `Resources`

**Comment by PatMyron** [comment]
@kddejong `v0.8.1`

`Don't believe this is a CloudFormation template. file:///Users/pmyron/Downloads/cfn-template.yaml. If it is please add AWSTemplateFormatVersion: '2010-09-09' (YAML) or  "AWSTemplateFormatVersion": "2010-09-09" (JSON) into the root level of the document.`

**Comment by PatMyron** [comment]
Current regex doesn't seem to work if `Resources:` is the first line of the template

**Comment by kddejong** [comment]
Closing. Should have this fixed shortly.  Thanks for pointing this out.

**Pull request closed without merging**
